// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VSAchitecture.Api.Data;

#nullable disable

namespace VSAchitecture.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("VSAchitecture.Api.Data.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeTelephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileTelephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Parents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9245fe4a-d402-451c-b9ed-9c1a04247482"),
                            Email = "john.doe@email.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Nationality = "",
                            OtherNames = "",
                            TimeStamp = new DateTime(2023, 9, 1, 23, 30, 1, 794, DateTimeKind.Utc).AddTicks(3440)
                        },
                        new
                        {
                            Id = new Guid("8245fe4a-d402-451c-b9ed-9c1a04247482"),
                            Email = "william.smith@email.com",
                            FirstName = "William",
                            LastName = "Smith",
                            Nationality = "",
                            OtherNames = "",
                            TimeStamp = new DateTime(2023, 9, 1, 23, 30, 1, 794, DateTimeKind.Utc).AddTicks(3490)
                        });
                });

            modelBuilder.Entity("VSAchitecture.Api.Data.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7245fe4a-d402-451c-b9ed-9c1a04247482"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Chalese",
                            LastName = "Doe",
                            Nationality = "",
                            OtherNames = "",
                            TimeStamp = new DateTime(2023, 9, 1, 23, 30, 1, 794, DateTimeKind.Utc).AddTicks(3500)
                        },
                        new
                        {
                            Id = new Guid("6245fe4a-d402-451c-b9ed-9c1a04247482"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joyce",
                            LastName = "Doe",
                            Nationality = "",
                            OtherNames = "",
                            TimeStamp = new DateTime(2023, 9, 1, 23, 30, 1, 794, DateTimeKind.Utc).AddTicks(3510)
                        },
                        new
                        {
                            Id = new Guid("5245fe4a-d402-451c-b9ed-9c1a04247482"),
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fredrick",
                            LastName = "Smith",
                            Nationality = "",
                            OtherNames = "",
                            TimeStamp = new DateTime(2023, 9, 1, 23, 30, 1, 794, DateTimeKind.Utc).AddTicks(3520)
                        });
                });

            modelBuilder.Entity("VSAchitecture.Api.Data.StudentParent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentParents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9875fe4a-d402-451c-b9ed-9c1a04247482"),
                            ParentId = new Guid("9245fe4a-d402-451c-b9ed-9c1a04247482"),
                            StudentId = new Guid("5245fe4a-d402-451c-b9ed-9c1a04247482")
                        },
                        new
                        {
                            Id = new Guid("9995fe4a-d402-451c-b9ed-9c1a04247482"),
                            ParentId = new Guid("9245fe4a-d402-451c-b9ed-9c1a04247482"),
                            StudentId = new Guid("6245fe4a-d402-451c-b9ed-9c1a04247482")
                        });
                });

            modelBuilder.Entity("VSAchitecture.Api.Data.StudentParent", b =>
                {
                    b.HasOne("VSAchitecture.Api.Data.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VSAchitecture.Api.Data.Student", "Student")
                        .WithMany("Parents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("VSAchitecture.Api.Data.Parent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("VSAchitecture.Api.Data.Student", b =>
                {
                    b.Navigation("Parents");
                });
#pragma warning restore 612, 618
        }
    }
}
